package mate.academy.backend.common.error;

public enum ErrorCode {
    VALIDATION_ERROR,
    INVALID_CREDENTIALS,
    EMAIL_ALREADY_REGISTERED,
    UNAUTHORIZED,
    FORBIDDEN,
    NOT_FOUND,
    GIFT_NOT_FOUND,
    ORDER_NOT_FOUND,
    USER_NOT_FOUND,
    BAD_REQUEST,
    INTERNAL_ERROR,
    ENDPOINT_NOT_FOUND,
    WISHLIST_ITEM_NOT_FOUND,
    WISHLIST_ITEM_ALREADY_EXISTS
}
